name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Nixpkgs input
        uses: DeterminateSystems/flake-checker-action@v3
        with:
          fail-mode: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Shellcheck
        run: nix-shell --run 'shellcheck $(find . -type f -name "*.sh" -executable)'
